kind: pipeline
name: default
steps:
  - name: environment
    image: docker.pkg.airfocus.dev/airfocus/airfocus-ci
    commands:
      - printenv
trigger:
  event:
    - push

---

kind: pipeline
name: deploy
steps:
  - name: environment
    image: docker.pkg.airfocus.dev/airfocus/airfocus-ci
    commands:
      - echo "DEPLOY"
trigger:
  event:
    - promote
    - tag
