image: node:0.12
git:
  path: github.com/choffmeister/drone-test
script:
  - apt-get update
  - apt-get install sudo
  - npm install
  - curl $REGISTRY_URL
publish:
  docker:
    image_name: choffmeister/drone-test
    docker_host: $DOCKER_HOST
    docker_version: 1.6.0
    registry_login: false
    registry_login_url: $REGISTRY_URL
    tags: [$DRONE_BRANCH, $(git rev-parse --short HEAD)]
    force_tags: true
    keep_build: false

